### ISSUE TITLE
analyzing current source file

### ISSUE THREAD

**Issue by ganesh1233456** [ink-analyzer/ink-analyzer#2]
```
// --snip--

#[cfg(test)]
mod tests {
    use ink_analyzer::Analysis;

    #[test]
    fn no_semantic_errors() {
        // read current file as a string literal
        let code = include_str!(file!());

        // run diagnostics
        let diagnostics = Analysis.diagnostics(code);

        // fail test if any diagnostics failed
        assert!(diagnostics.is_empty());
    }
}
```

hey @davidsemakula I am confused here. In this code `file!()` macro reads current file as string literal and after that it pass to the diagnostics as a `&str`. I have checked all the fails condition you have mentioned [here](https://github.com/ink-analyzer/ink-analyzer/blob/23f94f187ec3a4e41752e8cac3780541b204f219/src/analysis/diagnostics.rs#L84) in current source file and vscode already warn user before compiling code. Is that because of `ink-analyzer = "0.3.0"` package which is included in ink project? If so then why do we need to write analyzer test manually? it checks automatically isn't it?. This is just random thought may be this doesn't make sense 😁.
thanks!

**Comment by ganesh1233456** [comment]
> Hi @ganesh1233456 👋
> 
> > I am confused here. In this code file!() macro reads current file as string literal and after that it pass to the diagnostics as a &str.
> 
> Yes 🙂
> 
> > I have checked all the fails condition you have mentioned [here](https://github.com/ink-analyzer/ink-analyzer/blob/23f94f187ec3a4e41752e8cac3780541b204f219/src/analysis/diagnostics.rs#L84) in current source file and vscode already warn user before compiling code. Is that because of ink-analyzer = "0.3.0" package which is included in ink project? If so then why do we need to write analyzer test manually? it checks automatically isn't it?. This is just random thought may be this doesn't make sense
> 
> So as [mentioned here](https://github.com/ink-analyzer/ink-analyzer/issues/1#issuecomment-1474936342), this is not the best use case for ink! analyzer 🙂, I just wanted you to have a close example to how you'd typically talk to ink! analyzer through its public API as opposed to just repeating the internal unit tests. Take it as just a demo of how to use the interface, not as an example for how you'd really use ink! analyzer in a real project.
> 
> Ideally ink! analyzer will be running pre-compilation e.g. in an IDE/editor plugin/extension and showing you inline diagnostic errors (and along with other features) as you write the code. It essentially runs the same validation rules on your code as the ink! macro attribute does, but is better suited for IDE/editor environment where code is always changing and typically in some error state as you type. The ink! macro's parser is not very error resilient and expects well-formed code so it's great for it's primary job which is compilation but not for tooling like IDE integration where diagnostics and similar features have to be run as the user is typing and the user expects meaningful assistance even when the code is not in an error-free state.
> 
> So right now, your IDE/editor is aware of Rust language rules (via [rust-analyzer](https://rust-analyzer.github.io/) or [similar](https://www.jetbrains.com/rust/)), but it's completely unaware of ink!'s semantic rules. So you'll get inline errors, warnings and assists about low level Rust mistakes in the IDE but not about [high-level ink! mistakes](https://use.ink/macros-attributes/contract#anaylsis) (e.g. multiple `#[ink(storage)]` structs, no `#[ink(constructor)]` method e.t.c). ink! analyzer is going to help bring those features.
> 
> I'm currently working on VS Code extension that will probably make all of this very easier to understand with a demo in case I'm still not making sense 🙂. I will definitely ping you when more tools like that that use this library under the hood are available. Just curious, do you use VS Code or do you use some other editor/IDE?

yeah I use vscode @davidsemakula

**Comment by davidsemakula** [comment]
Hi @ganesh1233456 👋  

The first release of the VS Code extension is available at https://marketplace.visualstudio.com/items?itemName=ink-analyzer.ink-analyzer
Or you can get the VSIX directly from https://github.com/ink-analyzer/ink-vscode/releases

**Comment by ganesh1233456** [comment]
thanks @davidsemakula

**Comment by davidsemakula** [comment]
Hi @ganesh1233456 no pressure but just curious if you got a chance to checkout the VS Code extension 🙂.

There's also an introductory blog post for ink! analyzer at https://analyze.ink/blog/introducing-ink-analyzer if you're interested to find out more about the use case at a high level.
And a similar entry in the official ink! documentation portal at https://use.ink/getting-started/ink-analyzer/ (under "Third Party Tools and Libraries").
